Updated Watson SDK from 3.8.0 to 4.2.1 for Conversation and Discovery
watson-developer-cloud/conversation-enhanced pull request #118
Opened 2018-02-13 05:22 UTC by stevenpkg

2018-02-13 09:58 UTC, stevenpkg commented
The new collection id using NLU is 29a02155-3523-4f45-bd9e-7af848e016aa

2018-02-13 19:01 UTC, germanattanasio requested changes
This looks pretty good @stevenpkg. I left some comments.

Can you also format the code with two spaces? I think your IDE will automatically do it if you press `CMD`+`F`.

2018-02-13 19:01 UTC, germanattanasio commented on README.md
> +3. Create a new data collection, name it whatever you like, and select the default configuration. The default configuration now uses Natural Language Understanding ``NLU``.
Don't use `NLU`. We don't refer to services with acronyms

2018-02-13 19:01 UTC, germanattanasio commented on src/main/java/com/ibm/watson/apis/conversation_with_discovery/listener/SetupThread.java
> +      //QueryRequest.Builder queryBuilder = new QueryRequest.Builder(environmentId, collectionId);
remove commented code

2018-02-13 19:01 UTC, germanattanasio commented on src/main/java/com/ibm/watson/apis/conversation_with_discovery/rest/ProxyResource.java
> +      MessageResponse response = GsonSingleton.getGson().fromJson(sbuilder.toString(), MessageResponse.class);
why do we have empty lines here?

2018-02-13 19:01 UTC, germanattanasio commented on src/main/java/com/ibm/watson/apis/conversation_with_discovery/rest/ProxyResource.java
> +        new Conversation(API_VERSION != null ? API_VERSION : Constants.CONVERSATION_VERSION);
Let's default to `Constants.CONVERSATION_VERSION` no need to use the ternary operator

2018-02-13 19:01 UTC, germanattanasio commented on src/main/java/com/ibm/watson/apis/conversation_with_discovery/utils/Constants.java
> +  public static final String CONVERSATION_VERSION = Conversation.VERSION_DATE_2017_05_26;
Let's use Strings for our default values. We are going to remove the constants from our SDkKs

2018-02-13 19:01 UTC, germanattanasio commented on src/test/java/com/ibm/watson/apis/conversation_with_discovery/rest/ProxyResourceTest.java
> +    //assertEquals(serviceResponse.getTextConcatenated(" "), mockResponse.getTextConcatenated(" "));
remove commented code

2018-02-14 00:30 UTC, germanattanasio approved these changes

2018-02-14 00:30 UTC, merged