Update sdk for conversation and discover to 3.8 to fix bluemix problem
watson-developer-cloud/conversation-enhanced pull request #96
Opened 2017-06-08 04:20 UTC by stevenpkg

@germanattanasio this is an urgent fix for bluemix sdk update

2017-06-12 02:15 UTC, germanattanasio requested changes
Hi @stevenpkg, I left some comments, can you also add some test cases?

2017-06-12 02:15 UTC, germanattanasio commented on src/main/java/com/ibm/watson/apis/conversation_with_discovery/listener/SetupThread.java
> +      ConversationService service = new ConversationService(Constants.CONVERSATION_VERSION);
Use the constant from the SDK.

2017-06-12 02:15 UTC, germanattanasio commented on src/test/java/com/ibm/watson/apis/conversation_with_discovery/rest/ProxyResourceTest.java
>    public void testSendMessage() throws IOException, InterruptedException {
Why are you commenting this line?
Can you add tests cases for the changes you are doing?

2017-06-12 02:15 UTC, germanattanasio commented on build.gradle
> +    compile group: 'com.ibm.watson.developer_cloud', name: 'discovery', version:'3.8.0'
`okhttp` should be updated to 3.8.0

2017-06-13 02:45 UTC, stevenpkg commented on build.gradle
> +    compile group: 'com.ibm.watson.developer_cloud', name: 'discovery', version:'3.8.0'
//@Test
public void testSendMessage() throws IOException, InterruptedException {
       Test is broken with 3.8.0 update, and I needed to get a fix out quickly, will fix very soon

Use the constant from the SDK
      It does, just keeps it in one place Constants.java

2017-06-13 03:55 UTC, stevenpkg commented on build.gradle
> +    compile group: 'com.ibm.watson.developer_cloud', name: 'discovery', version:'3.8.0'
Fixed testSendMessage() by updating mockwebserver to 3.8.0

2017-06-14 00:55 UTC, stevenpkg commented
@germanattanasio can you please approve

2017-06-14 00:57 UTC, germanattanasio approved these changes

2017-06-14 00:59 UTC, germanattanasio commented
@stevenpkg you should make sure that the dependencies listed below are updated

```
    compile group: 'org.apache.solr', name: 'solr-solrj', version: '5.4.1'
    compile group: 'com.squareup.okhttp3', name: 'okhttp', version: '3.3.1'
    compile group: 'com.squareup.okhttp3', name: 'logging-interceptor', version: '3.3.1'
    compile group: 'com.squareup.okhttp3', name: 'okhttp-ws', version: '3.3.1'
    compile group: 'com.squareup.okhttp3', name: 'okhttp-urlconnection', version: '3.3.1'
    compile group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.3.6'
    compile group: 'org.apache.httpcomponents', name: 'httpcore', version: '4.3.2'
```

They all have problems with the new IBM JDK. We are doing a change to the SSL certificates we use and it will break this app after July 24 if you don't update the dependencies

2017-06-14 01:18 UTC, stevenpkg commented
@germanattanasio will update dependencies you listed

2017-06-28 19:18 UTC, merged